Fix Travis CI PRs builds and add copyrights (#52)
* Fix Travis CI PRs builds and add copyrights

* Update env-vars-check

* Update env-vars-check

* Update env-vars-check

diff --git a/scripts/env-vars-check b/scripts/env-vars-check
--- a/scripts/env-vars-check
+++ b/scripts/env-vars-check
@@ -1,4 +1,13 @@
 #!/usr/bin/env bash
+# Copyright (c) Microsoft. All rights reserved.
+# Note: Windows Bash doesn't support shebang extra params
+set -e
+
+# Do not run during Travis CI builds, to avoid failures in case of third party PRs
+if [[ "$TRAVIS_SECURE_ENV_VARS" == "false" ]]; then
+    echo "Info: skipping env vars check during Travis CI build"
+    exit 0
+fi
 
 if [[ -z "$PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING" ]]; then
     echo "Error: the PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING environment variable is not defined."
